version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "13000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  nginx:
    image: nginx:latest
    container_name: sandbox_nginx
    ports:
      - '80:80'
    volumes:
      - ./src:/code
      - ./conf.d:/etc/nginx/conf.d
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./src:/code
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: always
    links:
      - mysql:db
    ports:
      - '8082:80'
  redis:
    image: "redis:alpine"