version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: sandbox_nginx
    ports:
      - "80:80"
    volumes:
      - ${PWD}/code:/code
      - ${PWD}/conf.d:/etc/nginx/conf.d
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ${PWD}/code:/code