version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: sandbox_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/code
      - ./conf.d:/etc/nginx/conf.d
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./src:/code
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"